/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolios */
        get: operations["list_portfolios_portfolios_get"];
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Analytics */
        get: operations["get_portfolio_analytics_portfolios__portfolio_id__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolio Insights */
        get: operations["list_portfolio_insights_portfolios__portfolio_id__insights_get"];
        put?: never;
        /** Create Portfolio Insight */
        post: operations["create_portfolio_insight_portfolios__portfolio_id__insights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_portfolios__portfolio_id__transactions_get"];
        put?: never;
        /** Create Transaction */
        post: operations["create_transaction_portfolios__portfolio_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/transactions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Transaction Import */
        post: operations["commit_transaction_import_portfolios__portfolio_id__transactions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/transactions/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Transaction Import */
        post: operations["preview_transaction_import_portfolios__portfolio_id__transactions_import_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessTokenResponse */
        AccessTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** AnalysisSnapshotPageResponse */
        AnalysisSnapshotPageResponse: {
            /** Items */
            items: components["schemas"]["AnalysisSnapshotResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** AnalysisSnapshotResponse */
        AnalysisSnapshotResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Generator */
            generator: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            methodology: components["schemas"]["MethodologyResponse"];
            metrics: components["schemas"]["SnapshotMetricsResponse"];
            /** Model Name */
            model_name: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Summary */
            summary: string | null;
        };
        /** AssetWeightResponse */
        AssetWeightResponse: {
            /** Market Value */
            market_value: string;
            /** Symbol */
            symbol: string;
            /** Weight */
            weight: string;
        };
        /** CreatePortfolioRequest */
        CreatePortfolioRequest: {
            /**
             * Base Currency
             * @default USD
             */
            base_currency: string;
            /** Name */
            name: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** MethodologyResponse */
        MethodologyResponse: {
            /** Annual Risk Free Rate */
            annual_risk_free_rate: string;
            /** Annualization Periods */
            annualization_periods: number;
            /** Cash Flow Policy */
            cash_flow_policy: string;
            /** Date Alignment Policy */
            date_alignment_policy: string;
            /** Fee Policy */
            fee_policy: string;
            price_basis: components["schemas"]["PriceBasis"];
            return_type: components["schemas"]["ReturnType"];
            /**
             * Risk Free Rate As Of
             * Format: date
             */
            risk_free_rate_as_of: string;
            /** Risk Free Rate Assumption */
            risk_free_rate_assumption: string;
            /** Transaction Date Timezone */
            transaction_date_timezone: string;
            /** Valuation Method */
            valuation_method: string;
        };
        /** PortfolioAnalyticsResponse */
        PortfolioAnalyticsResponse: {
            /** Annualized Volatility */
            annualized_volatility: number | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Asset Weights */
            asset_weights: components["schemas"]["AssetWeightResponse"][];
            /** Cash Balance */
            cash_balance: string;
            /** Max Drawdown */
            max_drawdown: number | null;
            methodology: components["schemas"]["MethodologyResponse"];
            /** Portfolio Value */
            portfolio_value: string;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Simple Return */
            simple_return: number | null;
            /** Stale */
            stale: boolean;
        };
        /** PortfolioInsightResponse */
        PortfolioInsightResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Disclaimer */
            disclaimer: string;
            /** Generator */
            generator: string;
            /** Key Factors */
            key_factors: string[];
            /** Limitations */
            limitations: string[];
            /** Model Name */
            model_name: string | null;
            /** Prompt Version */
            prompt_version: string;
            risk_level: components["schemas"]["RiskLevel"];
            /** Stale */
            stale: boolean;
            /** Summary */
            summary: string;
        };
        /** PortfolioPageResponse */
        PortfolioPageResponse: {
            /** Items */
            items: components["schemas"]["PortfolioResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Base Currency */
            base_currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * PriceBasis
         * @enum {string}
         */
        PriceBasis: "adjusted_close";
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * ReturnType
         * @enum {string}
         */
        ReturnType: "simple";
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "moderate" | "high" | "insufficient_data";
        /** SnapshotAssetWeightResponse */
        SnapshotAssetWeightResponse: {
            /** Symbol */
            symbol: string;
            /** Weight */
            weight: string;
        };
        /** SnapshotMetricsResponse */
        SnapshotMetricsResponse: {
            /** Annualized Volatility */
            annualized_volatility: number | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Asset Weights */
            asset_weights: components["schemas"]["SnapshotAssetWeightResponse"][];
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Simple Return */
            simple_return: number | null;
            /** Stale */
            stale: boolean;
        };
        /** TransactionImportCommitResponse */
        TransactionImportCommitResponse: {
            /** Rows */
            rows: components["schemas"]["TransactionImportCommitRowResponse"][];
            summary: components["schemas"]["TransactionImportCommitSummaryResponse"];
        };
        /** TransactionImportCommitRowResponse */
        TransactionImportCommitRowResponse: {
            /** Errors */
            errors: components["schemas"]["TransactionImportIssueResponse"][];
            /** External Id */
            external_id: string | null;
            /** Row Number */
            row_number: number;
            status: components["schemas"]["TransactionImportRowStatus"];
            transaction: components["schemas"]["TransactionResponse"] | null;
        };
        /** TransactionImportCommitSummaryResponse */
        TransactionImportCommitSummaryResponse: {
            /** Created Rows */
            created_rows: number;
            /** Failed Rows */
            failed_rows: number;
            /** Replayed Rows */
            replayed_rows: number;
            /** Total Rows */
            total_rows: number;
        };
        /** TransactionImportIssueResponse */
        TransactionImportIssueResponse: {
            /** Code */
            code: string;
            /** Field */
            field: string | null;
            /** Message */
            message: string;
        };
        /** TransactionImportPreviewResponse */
        TransactionImportPreviewResponse: {
            /** Rows */
            rows: components["schemas"]["TransactionImportPreviewRowResponse"][];
            summary: components["schemas"]["TransactionImportPreviewSummaryResponse"];
        };
        /** TransactionImportPreviewRowResponse */
        TransactionImportPreviewRowResponse: {
            /** Errors */
            errors: components["schemas"]["TransactionImportIssueResponse"][];
            /** External Id */
            external_id: string | null;
            normalized: components["schemas"]["TransactionImportValueResponse"] | null;
            /** Row Number */
            row_number: number;
            status: components["schemas"]["TransactionImportRowStatus"];
        };
        /** TransactionImportPreviewSummaryResponse */
        TransactionImportPreviewSummaryResponse: {
            /** Invalid Rows */
            invalid_rows: number;
            /** Ready Rows */
            ready_rows: number;
            /** Replay Rows */
            replay_rows: number;
            /** Total Rows */
            total_rows: number;
        };
        /**
         * TransactionImportRowStatus
         * @enum {string}
         */
        TransactionImportRowStatus: "ready" | "replay" | "invalid" | "created" | "replayed" | "failed";
        /** TransactionImportValueResponse */
        TransactionImportValueResponse: {
            /** Cash Amount */
            cash_amount: string | null;
            /** External Id */
            external_id: string;
            /** Fees */
            fees: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Quantity */
            quantity: string | null;
            /** Symbol */
            symbol: string | null;
            transaction_type: components["schemas"]["TransactionType"];
            /** Unit Price */
            unit_price: string | null;
        };
        /** TransactionInput */
        TransactionInput: {
            /** Cash Amount */
            cash_amount?: number | string | null;
            /** External Id */
            external_id: string;
            /**
             * Fees
             * @default 0
             */
            fees: number | string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Quantity */
            quantity?: number | string | null;
            /** Symbol */
            symbol?: string | null;
            transaction_type: components["schemas"]["TransactionType"];
            /** Unit Price */
            unit_price?: number | string | null;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /** Cash Amount */
            cash_amount: string | null;
            /** External Id */
            external_id: string;
            /** Fees */
            fees: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /** Quantity */
            quantity: string | null;
            /** Symbol */
            symbol: string | null;
            transaction_type: components["schemas"]["TransactionType"];
            /** Unit Price */
            unit_price: string | null;
        };
        /**
         * TransactionType
         * @enum {string}
         */
        TransactionType: "BUY" | "SELL" | "DEPOSIT" | "WITHDRAWAL";
        /** UserResponse */
        UserResponse: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_portfolios_portfolios_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_portfolio_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePortfolioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_portfolio_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_portfolio_analytics_portfolios__portfolio_id__analytics_get: {
        parameters: {
            query: {
                /** @description Inclusive first date */
                start_date: string;
                /** @description Inclusive last date */
                end_date: string;
            };
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalyticsResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_portfolio_insights_portfolios__portfolio_id__insights_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSnapshotPageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_portfolio_insight_portfolios__portfolio_id__insights_post: {
        parameters: {
            query: {
                /** @description Inclusive first date */
                start_date: string;
                /** @description Inclusive last date */
                end_date: string;
            };
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioInsightResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_transactions_portfolios__portfolio_id__transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_transaction_portfolios__portfolio_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    commit_transaction_import_portfolios__portfolio_id__transactions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionImportCommitResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_transaction_import_portfolios__portfolio_id__transactions_import_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionImportPreviewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
